# Generated by Django 3.0.6 on 2020-06-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fst', models.CharField(max_length=300)),
                ('scd', models.CharField(max_length=300)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appy.A')),
            ],
        ),
    ]
